# Default log level
org.slf4j.simpleLogger.defaultLogLevel=debug

# this tool
org.slf4j.simpleLogger.log.no.catenda.docs.c4=debug

# Structurizr packages at DEBUG
org.slf4j.simpleLogger.log.com.structurizr=info

# Show date-time and short logger name
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.showShortLogName=true
